---
- hosts: all
  tasks: 
  - name: i want to ping all my ansible nodes or hosts
    ping:
     
  - name: i want to install webserver on ubuntu nodes
    apt: 
     name: apache2
     state: present  
