---
- hosts: all
  become: yes
  tasks: 
  - name: i want to ping all my ansible nodes or hosts
    ping: 
  - name: i want to install web server on ubuntu nodes
    apt: 
     name: apache2
     state: present

  - name: i want to install git
    apt: 
     name: git
     state: present
