---
- hosts: 172.31.8.97
  become: yes
  tasks: 
  - name: i want to know host name
    command: hostname -f
    register: myresult
  - name: i want to debug my result
    debug: 
     msg: "{{myresult}}"
  - name: i want to install git
    apt: 
     name: git
     state: present
    when: myresult.stderr==""
  - name: iwant to install tree
    apt: 
     name: tree
     state: present
    when: myresult.stderr!=""     
