---
- hosts: 172.31.8.97
  become: yes
  tasks: 
  - name: install git
    apt:
     name: git
  - nam e: install wget
    apt:
     name: wget
    ignore_errors: yes
  - name: install tree
    apt: 
     name: tree
