---
- hosts: all
  become: yes
  tasks: 
  - name: i want to ping all my ansible nodes or hosts
    ping: 
  - name: i want to install web server on ubuntu nodes
    apt: 
     name: apache2
    when: ansible_os_family=="Debian"
  - name: i want to install webserver on RedHat
    yum:
     name: httpd
    when: ansible_os_family=="RedHat"
